use chacha20poly1305::{
    aead::{Aead, KeyInit},
    ChaCha20Poly1305, Nonce,
};
use rand::{rngs::OsRng, RngCore};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::{
    env,
    fs::{self, File},
    io::{self, Read, Write},
    net::{TcpListener, TcpStream, UdpSocket},
    path::Path,
    time::{Duration, Instant},
};

type Result<T> = std::result::Result<T, Box<dyn std::error::Error>>;
const BLOCK: usize = 64 * 1024;
const QUERY: &[u8] = b"LAN-TRANSFER-PROTOTYPE/1";
#[derive(Serialize, Deserialize)]
struct Offer {
    name: String,
    size: u64,
}
#[derive(Serialize, Deserialize)]
struct Device {
    protocol: String,
    name: String,
    port: u16,
}
fn fail(s: &str) -> Box<dyn std::error::Error> {
    io::Error::new(io::ErrorKind::InvalidData, s).into()
}
fn cipher() -> Result<[u8; 32]> {
    let s = env::var("LAN_TRANSFER_KEY")
        .map_err(|_| fail("Set LAN_TRANSFER_KEY to the 64-character key generated by keygen"))?;
    if s.len() != 64 || !s.is_ascii() {
        return Err(fail("Invalid key"));
    }
    let key: Vec<u8> = (0..64)
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16))
        .collect::<std::result::Result<_, _>>()?;
    key.try_into().map_err(|_| fail("Invalid key"))
}
// A random connection ID derives a fresh session key. A shared monotonically
// increasing frame counter authenticates ordering in this half-duplex protocol.
struct Channel {
    cipher: ChaCha20Poly1305,
    prefix: [u8; 4],
    sequence: u64,
}
impl Channel {
    fn new(base: &[u8; 32], stream: &mut TcpStream, sender: bool) -> Result<Self> {
        let mut id = [0u8; 64];
        if sender {
            OsRng.fill_bytes(&mut id[..32]);
            stream.write_all(&id[..32])?;
            stream.read_exact(&mut id[32..])?;
        } else {
            stream.read_exact(&mut id[..32])?;
            OsRng.fill_bytes(&mut id[32..]);
            stream.write_all(&id[32..])?;
        }
        let hk = hkdf::Hkdf::<Sha256>::new(Some(&id), base);
        let mut key = [0u8; 32];
        hk.expand(b"lan-transfer-prototype/1", &mut key)
            .map_err(|_| fail("Key derivation failed"))?;
        Ok(Self {
            cipher: ChaCha20Poly1305::new_from_slice(&key)?,
            prefix: [0; 4],
            sequence: 0,
        })
    }
    fn nonce(&mut self) -> Result<[u8; 12]> {
        let mut n = [0; 12];
        n[..4].copy_from_slice(&self.prefix);
        n[4..].copy_from_slice(&self.sequence.to_be_bytes());
        self.sequence = self
            .sequence
            .checked_add(1)
            .ok_or_else(|| fail("Frame limit"))?;
        Ok(n)
    }
    fn write(&mut self, s: &mut TcpStream, bytes: &[u8]) -> Result<()> {
        let nonce = self.nonce()?;
        let data = self
            .cipher
            .encrypt(Nonce::from_slice(&nonce), bytes)
            .map_err(|_| fail("Encryption failed"))?;
        s.write_all(&(data.len() as u32).to_be_bytes())?;
        s.write_all(&data)?;
        Ok(())
    }
    fn read(&mut self, s: &mut TcpStream) -> Result<Vec<u8>> {
        let mut len = [0; 4];
        s.read_exact(&mut len)?;
        let len = u32::from_be_bytes(len) as usize;
        if !(16..=BLOCK + 16).contains(&len) {
            return Err(fail("Invalid frame size"));
        }
        let mut data = vec![0; len];
        s.read_exact(&mut data)?;
        let nonce = self.nonce()?;
        self.cipher
            .decrypt(Nonce::from_slice(&nonce), data.as_ref())
            .map_err(|_| fail("Wrong key or damaged/out-of-order frame"))
    }
}
fn safe_name(name: &str) -> bool {
    if name.is_empty()
        || name.len() > 180
        || name.ends_with(['.', ' '])
        || name
            .chars()
            .any(|c| c.is_control() || "<>:\"/\\|?*".contains(c))
    {
        return false;
    }
    let base = name.split('.').next().unwrap_or("").to_uppercase();
    !matches!(base.as_str(), "" | "CON" | "PRN" | "AUX" | "NUL")
        && !(1..=9).any(|i| base == format!("COM{i}") || base == format!("LPT{i}"))
}
fn configure(s: &TcpStream) -> Result<()> {
    s.set_read_timeout(Some(Duration::from_secs(15)))?;
    s.set_write_timeout(Some(Duration::from_secs(15)))?;
    Ok(())
}
fn receive(mut s: TcpStream, base: &[u8; 32], dir: &Path) -> Result<()> {
    configure(&s)?;
    let mut ch = Channel::new(base, &mut s, false)?;
    let offer: Offer = serde_json::from_slice(&ch.read(&mut s)?)?;
    if !safe_name(&offer.name) || offer.size > 100 * 1024 * 1024 * 1024 {
        return Err(fail(
            "Invalid name or file larger than 100 GiB prototype limit",
        ));
    }
    let mut temp = tempfile::NamedTempFile::new_in(dir)?;
    ch.write(&mut s, b"READY")?;
    let start = Instant::now();
    let mut received = 0;
    let mut hash = Sha256::new();
    while received < offer.size {
        let data = ch.read(&mut s)?;
        if data.is_empty() || data.len() as u64 > offer.size - received {
            return Err(fail("Invalid data length"));
        }
        temp.write_all(&data)?;
        hash.update(&data);
        received += data.len() as u64;
    }
    if ch.read(&mut s)? != hash.finalize().as_slice() {
        return Err(fail("Checksum mismatch"));
    }
    temp.as_file().sync_all()?;
    let mut name = offer.name.clone();
    for i in 1..=10000 {
        match temp.persist_noclobber(dir.join(&name)) {
            Ok(_) => {
                ch.write(&mut s, name.as_bytes())?;
                println!(
                    "Received {} bytes in {:.3}s: {}",
                    received,
                    start.elapsed().as_secs_f64(),
                    name
                );
                return Ok(());
            }
            Err(e) if e.error.kind() == io::ErrorKind::AlreadyExists => {
                temp = e.file;
                name = format!("{i}-{}", offer.name);
            }
            Err(e) => return Err(e.error.into()),
        }
    }
    Err(fail("Too many duplicate filenames"))
}
fn serve(dir: &Path, bind: &str, name: &str) -> Result<()> {
    let base = cipher()?;
    fs::create_dir_all(dir)?;
    let listener = TcpListener::bind(bind)?;
    let addr = listener.local_addr()?;
    let udp = UdpSocket::bind(addr)?;
    let device = serde_json::to_vec(&Device {
        protocol: "lan-transfer-prototype/1".into(),
        name: name.into(),
        port: addr.port(),
    })?;
    std::thread::spawn(move || {
        let mut buf = [0; 256];
        loop {
            match udp.recv_from(&mut buf) {
                Ok((n, peer)) if &buf[..n] == QUERY => {
                    let _ = udp.send_to(&device, peer);
                }
                Ok(_) => {}
                Err(_) => break,
            }
        }
    });
    println!("Listening on {addr}; receive folder: {}", dir.display());
    println!("Prototype: holders of the shared key can send files automatically. Ctrl+C stops.");
    for s in listener.incoming() {
        match s {
            Ok(s) => {
                if let Err(e) = receive(s, &base, dir) {
                    eprintln!("Transfer rejected/failed: {e}");
                }
            }
            Err(e) => eprintln!("Connection failed: {e}"),
        }
    }
    Ok(())
}
fn discover(target: Option<&str>) -> Result<()> {
    let udp = UdpSocket::bind("0.0.0.0:0")?;
    udp.set_broadcast(true)?;
    udp.set_read_timeout(Some(Duration::from_millis(250)))?;
    let mut targets = std::collections::HashSet::new();
    if let Some(target) = target {
        targets.insert(target.to_owned());
    } else {
        for interface in if_addrs::get_if_addrs()? {
            if let if_addrs::IfAddr::V4(v4) = interface.addr {
                if !v4.ip.is_loopback() {
                    if let Some(broadcast) = v4.broadcast {
                        targets.insert(format!("{broadcast}:45873"));
                    }
                }
            }
        }
        if targets.is_empty() {
            return Err(fail(
                "No IPv4 LAN interface; connect to a LAN or specify IP:port",
            ));
        }
    }
    let mut sent = false;
    for target in targets {
        match udp.send_to(QUERY, &target) {
            Ok(_) => sent = true,
            Err(e) => eprintln!("Discovery unavailable on {target}: {e}"),
        }
    }
    if !sent {
        return Err(fail(
            "Discovery could not reach a network; try sending directly to the other computer's IP",
        ));
    }
    let start = Instant::now();
    let mut seen = std::collections::HashSet::new();
    let mut buf = [0; 1024];
    while start.elapsed() < Duration::from_secs(3) {
        match udp.recv_from(&mut buf) {
            Ok((n, peer)) => {
                if let Ok(d) = serde_json::from_slice::<Device>(&buf[..n]) {
                    if d.protocol == "lan-transfer-prototype/1" && seen.insert(peer.ip()) {
                        println!("{}\t{}:{}", d.name, peer.ip(), d.port);
                    }
                }
            }
            Err(e)
                if matches!(
                    e.kind(),
                    io::ErrorKind::WouldBlock | io::ErrorKind::TimedOut
                ) => {}
            Err(e) => return Err(e.into()),
        }
    }
    if seen.is_empty() {
        println!("No devices found; try a subnet broadcast address or send directly to IP:port.");
    }
    Ok(())
}
fn send(addr: &str, path: &Path) -> Result<()> {
    let base = cipher()?;
    let mut file = File::open(path)?;
    let metadata = file.metadata()?;
    if !metadata.is_file() {
        return Err(fail("Only regular files supported"));
    }
    let name = path
        .file_name()
        .and_then(|s| s.to_str())
        .ok_or_else(|| fail("Filename is not UTF-8"))?;
    if !safe_name(name) {
        return Err(fail("Filename is not portable to Windows"));
    }
    use std::net::ToSocketAddrs;
    let addr = addr
        .to_socket_addrs()?
        .next()
        .ok_or_else(|| fail("No address"))?;
    let mut s = TcpStream::connect_timeout(&addr, Duration::from_secs(5))?;
    configure(&s)?;
    let mut ch = Channel::new(&base, &mut s, true)?;
    ch.write(
        &mut s,
        &serde_json::to_vec(&Offer {
            name: name.into(),
            size: metadata.len(),
        })?,
    )?;
    if ch.read(&mut s)? != b"READY" {
        return Err(fail("Receiver not ready"));
    }
    let start = Instant::now();
    let mut remaining = metadata.len();
    let mut buf = vec![0; BLOCK];
    let mut hash = Sha256::new();
    while remaining > 0 {
        let limit = (remaining as usize).min(BLOCK);
        let n = file.read(&mut buf[..limit])?;
        if n == 0 {
            return Err(fail("Source file changed/truncated"));
        }
        ch.write(&mut s, &buf[..n])?;
        hash.update(&buf[..n]);
        remaining -= n as u64;
    }
    ch.write(&mut s, &hash.finalize())?;
    let saved = ch.read(&mut s)?;
    println!(
        "Sent {} bytes in {:.3}s; saved as {}",
        metadata.len(),
        start.elapsed().as_secs_f64(),
        String::from_utf8_lossy(&saved)
    );
    Ok(())
}
fn run() -> Result<()> {
    let a: Vec<String> = env::args().collect();
    match a.get(1).map(String::as_str) {
        Some("keygen") => {
            let mut key = [0; 32];
            OsRng.fill_bytes(&mut key);
            println!(
                "{}",
                key.iter().map(|b| format!("{b:02x}")).collect::<String>()
            );
            Ok(())
        }
        Some("receive") => serve(
            Path::new(a.get(2).map(String::as_str).unwrap_or("received")),
            a.get(3).map(String::as_str).unwrap_or("0.0.0.0:45873"),
            a.get(4).map(String::as_str).unwrap_or("My computer"),
        ),
        Some("discover") => discover(a.get(2).map(String::as_str)),
        Some("send") if a.len() == 4 => send(&a[2], Path::new(&a[3])),
        _ => {
            println!("lan-transfer keygen\nlan-transfer receive [folder] [bind-IP:port] [device-name]\nlan-transfer discover [broadcast-IP:port]\nlan-transfer send IP:port file\nSet LAN_TRANSFER_KEY to the same generated key on both devices.");
            Ok(())
        }
    }
}
fn main() {
    if let Err(e) = run() {
        eprintln!("Error: {e}");
        std::process::exit(1);
    }
}
#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn rejects_nonportable_paths() {
        for s in [
            "../a", "..", "a/b", "a\\b", "C:a", "CON.txt", "NUL", "LPT1.zip", "a.", "a\n",
        ] {
            assert!(!safe_name(s), "{s}");
        }
        for s in ["中文文件.txt", "photo.jpg", "test file.zip"] {
            assert!(safe_name(s));
        }
    }
    #[test]
    fn interrupted_and_corrupt_uploads_leave_no_files() {
        for corrupt in [false, true] {
            let dir = tempfile::tempdir().unwrap();
            let target = dir.path().to_path_buf();
            let listener = TcpListener::bind("127.0.0.1:0").unwrap();
            let address = listener.local_addr().unwrap();
            let worker = std::thread::spawn(move || {
                let (stream, _) = listener.accept().unwrap();
                assert!(receive(stream, &[7; 32], &target).is_err());
            });
            let mut stream = TcpStream::connect(address).unwrap();
            configure(&stream).unwrap();
            let mut channel = Channel::new(&[7; 32], &mut stream, true).unwrap();
            channel
                .write(
                    &mut stream,
                    &serde_json::to_vec(&Offer {
                        name: "sample.bin".into(),
                        size: 10,
                    })
                    .unwrap(),
                )
                .unwrap();
            assert_eq!(channel.read(&mut stream).unwrap(), b"READY");
            if corrupt {
                stream.write_all(&32u32.to_be_bytes()).unwrap();
                stream.write_all(&[0; 32]).unwrap();
            } else {
                channel.write(&mut stream, b"partial").unwrap();
            }
            drop(stream);
            worker.join().unwrap();
            assert_eq!(fs::read_dir(dir.path()).unwrap().count(), 0);
        }
    }
}
